#!/usr/bin/env bash
set -e

CYAN="\033[0;36m"
YELLOW="\033[0;33m"
GREEN="\033[0;32m"
RESET="\033[0m"

echo
echo -e "Making /bin directory"
mkdir -p bin
mkdir -p bin/fonts
mkdir -p bin/img

echo
echo -e "${CYAN}JS${RESET}"
echo -e "Combining all at ${CYAN}public/js/*.js${RESET}"
cat public/js/*.js > bin/main.js
echo -e "Minimizing"
node_modules/.bin/uglifyjs bin/main.js > bin/main.min.js

echo
echo -e "${GREEN}CSS${RESET}"
echo -e "Combining all at ${GREEN}public/css/*.css${RESET}"
cat public/css/*.css > bin/style.css
echo -e "Minimizing"
node_modules/.bin/cleancss bin/style.css > bin/style.min.css

echo
echo -e "${YELLOW}HTML${RESET}"
echo -e "Combining all HTML and Templates..."
cat public/html/begin.html > bin/tmp.html
cat public/html/head-production.html >> bin/tmp.html
cat public/html/begin-body.html >> bin/tmp.html
cat public/html/body.html >> bin/tmp.html
cat public/templates/*.html >> bin/tmp.html
cat public/html/end.html >> bin/tmp.html
mv bin/tmp.html bin/index.html

echo
echo -e "Copying assets..."
cp -fr public/fonts/ bin/fonts/
cp -fr public/img/ bin/img/
cp -fr public/favicon.ico bin/favicon.ico

echo
echo "Done."
