#!/usr/bin/env bash
set -e

CYAN="\033[0;36m"
YELLOW="\033[0;33m"
GREEN="\033[0;32m"
RESET="\033[0m"

echo
echo -e "Making \"bin\" directory"
mkdir -p bin

echo
echo -e "Linking assets"
ln -fs ../src/fonts bin/fonts
ln -fs ../src/img bin/img
ln -fs ../src/css bin/css
ln -fs ../src/js bin/js
ln -fs ../src/favicon.ico bin/favicon.ico

echo
echo -e "${YELLOW}HTML${RESET}"
echo -e "Combining all HTML and Templates..."


cat src/html/begin.html > bin/tmp.html
gawk -v root=src -f scripts/stamp-qs.awk < src/html/head.html >> bin/tmp.html
cat src/html/begin-body.html >> bin/tmp.html
cat src/html/body.html >> bin/tmp.html
cat src/templates/*.html >> bin/tmp.html
cat src/html/end.html >> bin/tmp.html
mv bin/tmp.html bin/index.html


echo
echo "Done."
