#!/usr/bin/env bash
set -e

CYAN="\033[0;36m"
YELLOW="\033[0;33m"
GREEN="\033[0;32m"
RESET="\033[0m"

echo
echo -e "Making \"bin\" directory"
mkdir -p bin

echo
echo -e "Linking assets"

rm -f $PWD/bin/fonts
ln -s $PWD/src/fonts       $PWD/bin/fonts

rm -f $PWD/bin/img
ln -s $PWD/src/img         $PWD/bin/img

rm -f $PWD/bin/css
ln -s $PWD/src/css         $PWD/bin/css

rm -f $PWD/bin/js
ln -s $PWD/src/js          $PWD/bin/js

rm -f $PWD/bin/favicon.ico
ln -s $PWD/src/favicon.ico $PWD/bin/favicon.ico

echo
echo -e "${YELLOW}HTML${RESET}"
echo -e "Combining all HTML and Templates..."


cat src/html/begin.html > bin/tmp.html
gawk -v root=src -f scripts/stamp-qs.awk < src/html/head.html >> bin/tmp.html
cat src/html/begin-body.html >> bin/tmp.html
cat src/html/body.html >> bin/tmp.html
cat src/templates/*.html >> bin/tmp.html
cat src/html/end.html >> bin/tmp.html
mv bin/tmp.html bin/index.html


echo
echo "Done."
