var strings = {
  "error": "An error occured.",
  "createPlaylist": "Give a name for new playlist.",
  "renamePlaylist": "Give a new name for this playlist.",
  "destroyPlaylist": "Are you sure you want to remove this playlist?",
  "accountUpdated": "Your account information has been saved.",
  "settingsUpdated": "Your preferred settings have been updated.",
  "shopEmailUpdated": "Your shop email has been updated.",
  "addedToPlaylist": "Song succesfully added to playlist.",
  "reorderedPlaylist": "Playlist order saved.",
  "removedFromPlaylist": "Song succesfully removed from playlist.",
  "passwordMissing": "You must enter a password.",
  "passwordReset": "Your password has been reset. Please sign in.",
  "passwordResetEmail": "Check your email for a link to reset your password.",
  "twoFactorConfirmed": "Two-factor authentication has been enabled.",
  "twoFactorPending": "Two-factor authentication pending. Enter the token sent to you to confirm.",
  "twoFactorDisabled": "Two-factor authentication has been removed.",
  "tokenResent": "A new Two-factor authentication token has been sent.",
  "noAccount": "You do not have an account, would you like to create one?",
  "claimReleased": "Your claim has been succesfully removed.",
  "unsubscribeGold": "Are you sure you want to unsubscribe from the Gold Membership?",
  "unsubscribeWhitelist": "Are you sure you want to cancel your license subscription? The whitelisting will be removed at the end of your payment period.",
  "goldAdded": "Gold Membership was added to your cart. Check below!",
  "whitelistAdded": "The license was added to your cart. Check below!",
  "cart5": "You can only purchase up to 5 subscriptions at a time.",
  "goldInCart": "The Gold Membership is already in your cart.",
  "licenseInCart": "The license is already in your cart or is already purchased.",
  "cancelWhitelistSub": "Are you sure you want to cancel this subscription?",
  "codeNotFound": "The code you entered does not exist.",
  "codeNotValid": "The code you entered is not valid any more.",
  "invalidIdentity": "The channel you tried to add is not valid.",
  "unavailableIdentity": "The identity is already in use."
}
