#!/usr/bin/env bash
set -e

SRC=$PWD/src
HTML=$SRC/html
TEMPLATES=$(find "$SRC/templates" -iname '*.html')

web-build $HTML/begin.html \
  $HTML/${1:-development}.html \
	$HTML/head.html \
	$HTML/begin-body.html \
	$HTML/body.html \
	$TEMPLATES \
	$HTML/end.html \
	serve -m -v --static $SRC --port ${2:-8080}
