#!/usr/bin/env bash
set -e

SRC=$PWD/src
HTML=$SRC/html
TEMPLATES=$(find "$SRC/templates" -iname '*.html')

web-build $HTML/begin.html \
	$HTML/head.html \
	$HTML/begin-body.html \
	$HTML/body.html \
	$TEMPLATES \
	$HTML/end.html \
	serve --static $SRC --port ${1:-8080}
